app_homepage:
    path: /
    controller: App\Controller\QuestionController::homepage

app_show:
    path: /show/{slug}
    controller: App\Controller\QuestionController::show

app_comment_vote:
    path: /comments/{id}/vote/{direction<up|down>}
    controller: App\Controller\CommentController::commentVote
    methods: ['POST']

